version: "3.9"
services:
  js:
    image: node
    env_file: .env
    volumes:
      - ./js:/app
    working_dir: /app
    ports:
      - ${JS_PORT}:3000
    restart: on-failure:10
    entrypoint: bash -c "npm i && node server.js"
