version: "3.9"
services:
  js:
    image: node
    env_file: .env
    volumes:
      - ./js:/app
    working_dir: /app
    ports:
      - ${JS_PORT}:3000
    restart: on-failure:10
    entrypoint: bash -c "npm i && node server.js"

  py:
    image: python
    env_file: .env
    volumes:
      - ./py:/app
    working_dir: /app
    ports:
     - ${PY_PORT}:5000
    restart: on-failure:10
    entrypoint: bash -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 5000 --proxy-headers"
